# Generated by Django 4.0.2 on 2022-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='petstore',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
