# Generated by Django 4.0.2 on 2022-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstores', '0002_alter_employee_contact_alter_petstore_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
