# Generated by Django 4.0.2 on 2022-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstores', '0004_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='breed',
            field=models.ManyToManyField(related_name='breed_name', to='petstores.Breed'),
        ),
    ]
