# Generated by Django 4.0.2 on 2022-05-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstores', '0005_alter_sale_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='breed',
            field=models.ManyToManyField(related_name='sale', to='petstores.Breed'),
        ),
    ]
