# Generated by Django 4.0.3 on 2022-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_age', models.IntegerField()),
                ('teacher_address', models.CharField(max_length=100)),
            ],
        ),
    ]
